version: '3.3'
services:
  database:
    image: mysql
    volumes:
      - './database/data/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    env_file:
      - database/.docker.env
  server:
    image: nodeapp
    ports:
      - '3333:3333'
    volumes:
      - './server/:/usr/tilas/'
      - './server.dev.env:/usr/tilas/.env'
    build: ./server/
    depends_on:
      - database
