version: '3.3'
services:

  mongo:
    image: mongo:latest
    volumes:
      - './database/data/mongo:/data/db'
    ports:
      - '27017:27017'
    env_file:
      - database/docker.env

  auth:
    ports:
      - '3333:3333'
      - '9229:9229'
    volumes:
      - './auth/:/usr/tilas/auth/'
    build: ./auth/
    depends_on:
      - mongo

  client:
    ports:
      - '80:80'
    volumes:
      - './client/:/usr/tilas/client/'
    build: ./client/
    env_file:
      - client/docker.env
    depends_on:
      - server
