version: '3.3'
services:

  database:
    image: mysql
    volumes:
      - './database/data/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    env_file:
      - database.docker.env

  server:
    ports:
      - '3333:3333'
    volumes:
      - './server/:/usr/tilas/server/'
      - './server.dev.env:/usr/tilas/server/.env'
    build: ./server/
    depends_on:
      - database

  client:
    ports:
      - '80:80'
    volumes:
      - './client/:/usr/tilas/client/'
    build: ./client/
    env_file:
      - client.docker.env
    depends_on:
      - server
